# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60e64f91b7e6114027bd311be2c8bbe235f4738d9b3c0195b8ee029061e71e9db6bfcb05d473e685da45355f3400fc5c34ee1671b6d87d208e83a3e91690dc98

test:
  secret_key_base: acf3a38a73b7cee1c973dafe1c06de47ba8ffbbdc93dfa64ebd226f4929cfb8d0ce8b34f4b98f3bff3c7d4bfd552e53c4d7b79ddd20121f670177e3f22eb4780

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
